### PR TITLE
Add Javadoc documentation to a lot of classes.

### PR DESCRIPTION
**Pull request by mjuvekar7**
Add Javadoc to 56 classes of the WorkstationCrafting module.

### CODE REVIEW

**Comment by Cervator** [comment]
Approved this in GCI (https://codein.withgoogle.com/dashboard/task-instances/5012104773894144/) but some of the affected classes were moved out to other modules like Smithing via #4 - the JavaDoc should still fully apply but we need to move some of it across to the new module(s). 

Should be easy to do, just a bit of hassle. No rush on it and any of us can do it, just need to find some free time to finish that :-)

**Comment by skaldarnar** [comment]
@mjuvekar7 are you still around to look into this? I'd like to get this merged as it is a valuable contribution to the project!

**Comment by mjuvekar7** [comment]
Yep I'm there

**Comment by mjuvekar7** [comment]
Fixed conflicts. Committed with a bad commit message by mistake (I guess that could be fixed while merging)

**Comment by mjuvekar7** [comment]
https://github.com/Terasology/WoodCrafting/pull/2
https://github.com/Terasology/StoneCrafting/pull/1

The PRs in WoodCrafting and StoneCrafting related to this.

**Pull request merged**
